### ISSUE TITLE
Datum letztes Login

### ISSUE THREAD

**Issue by aui01** [JWManagement/JWManagement#433]
In der Datenbank muss es die Daten geben, wann ein User das letzte mal  online war. Unter Projektname/Verkündiger  ist je user ein letztes Login vermerkt. Das ist bei meinem persönlichen Login falsch. Ich war in den letzten Tagen, speziell am 20.06.2022 und 21.06.2022 mehrfach online. Vermerkt ist aber 2020-09-07

Hier ging es schonmal um dieses Datenbankfeld:
https://github.com/JWManagement/JWManagement/pull/364/files/96fb5f291c66be8ce843084c5f4c22d58ce42e9d

**Comment by tim-antkowiak** [comment]
Tatsächlich scheint die Funktion irgendwann ausgebaut worden zu sein. Zumindest habe ich keine Stelle mehr gefunden, wo das Feld gesetzt worden wäre.
Hotfix ist in Arbeit.

**Comment by tim-antkowiak** [comment]
Hab den Fix mal deployed @aui01. Magst du mal probieren ob jetzt das richtige Datum angezeigt wird?

Spannend wäre die Frage, was mit denen passiert, die die ganze Zeit angemeldet bleiben, also sich nicht ausloggen, ob das Feld da auch irgendwann geupdated wird.
Mal sehen.

**Comment by aui01** [comment]
Sieht bei mir gut aus 👍🏻 Datum von heute wurde gleich nach Login gezogen. Danke dir 👌🏻
