### ISSUE TITLE
user import via CSV doesn't check if users already exist

### ISSUE THREAD

**Issue by aui01** [JWManagement/JWManagement#434]
Loading up a CSV with users once creates them. Doing it twice creates them twice. That should not be. Wiki says JWM is looking for exisiting Users, which seems not to happen...but should...read here:
https://github.com/JWManagement/JWManagement/wiki/Benutzer

See project MMkbjej5WamtrA5pT

**Comment by dcolumbus** [comment]
We just experienced the same issue. And when a duplicate user attempts to log in, they are told that there are multiple accounts under the same email address.

I have removed all duplicate users from the project, but I don't see an option to remove duplicate users completely from the application.

**Comment by tim-antkowiak** [comment]
It seems the checking for existing users were removed a while ago (see a48e0a0).

At the moment the modal is just for adding new users to a project. As @dcolumbus mentioned, the user will be prompted after login so the user can merge the accounts into one.

A bulk update of users seemst to be not supported at the moment.

**Comment by aloosen** [comment]
It seems that this feature is being used by many project managers. Obviously, bulk update was removed, because the id that was used for reference was the email address, and we don't enforce uniqueness of email addresses. But we could easily export the user id in the CSV file, and because that _is_ unique,  we can update pushlishers.

**Comment by tim-antkowiak** [comment]
Right, that would be possible. But not sure if that is conform with the new data protection policies. Because that would mean that project admins have the possibility to update and add personal data for other users.

**Comment by aui01** [comment]
We should really talk about this within the next days. For me this is a key feature too. Admins should be able to do this. And as far as I can see, even the european laws wouldn't be violated...

**Comment by tim-antkowiak** [comment]
I agree, as far as you get the permission from the user you can nearly do everything with personal data. The question is if we want that. But that's something the organisators need to decide, not we as developer.

**Comment by aui01** [comment]
Would appreciate if this could be fixed for the next version.

**Comment by aui01** [comment]
@aloosen @tim-antkowiak One of the admins found a bug (which I was able to reproduce): editing **project-permissions** for existing users via 
1.) csv-download --> 2.) change permissions in csv --> 3.)csv-upload 
isn't working. All the other changes are successful, such as language, congregation and even tag permissions.

As far as I could see project-permissions can be changed if downgraded (from admin to member) but not if upgraded (member to shiftmanager and upwards).

**Comment by aui01** [comment]
sorry, my bad. closed now again.
